// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"Payment-Terminal-Management/internal/config"
	"Payment-Terminal-Management/internal/handler"
	"Payment-Terminal-Management/internal/middleware"
	"Payment-Terminal-Management/internal/service"
	"Payment-Terminal-Management/internal/session"
	"Payment-Terminal-Management/internal/transport"
	"Payment-Terminal-Management/internal/worker"
	"github.com/google/wire"
	"net"
	"os"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	listener, err := ProvideListener()
	if err != nil {
		return nil, err
	}
	sessionManager := session.NewSessionManager()
	kafkaProducerConfig := config.LoadKafkaProducerConfig()
	writer := middleware.CreateKafkaProducer(kafkaProducerConfig)
	kafkaProducerWorkerImpl := worker.NewProducerWorker(writer)
	producerService := service.NewProduceService(kafkaProducerWorkerImpl)
	kafkaConsumerConfig := config.LoadKafkaConsumerConfig()
	reader := middleware.CreateKafkaConsumer(kafkaConsumerConfig)
	kafkaConsumerWorker := worker.NewConsumerWorker(reader)
	transactionNotiHandler := handler.NewTransactionNotiHandler(sessionManager, kafkaProducerWorkerImpl)
	consumerService := service.NewConsumerService(kafkaConsumerWorker, sessionManager, transactionNotiHandler)
	server := transport.NewServer(sessionManager, producerService, consumerService)
	app := NewApp(listener, server, consumerService)
	return app, nil
}

// wire.go:

func ProvideListener() (net.Listener, error) {
	port := os.Getenv("PORT")
	if port == "" {
		port = "8089"
	}
	return net.Listen("tcp", ":"+port)
}

var ProducerSet = wire.NewSet(config.LoadKafkaProducerConfig, middleware.CreateKafkaProducer, worker.NewProducerWorker, service.NewProduceService, wire.Bind(new(worker.KafkaProducerWorker), new(*worker.KafkaProducerWorkerImpl)))

var ConsumerSet = wire.NewSet(config.LoadKafkaConsumerConfig, middleware.CreateKafkaConsumer, worker.NewConsumerWorker, service.NewConsumerService)

var ServerSet = wire.NewSet(transport.NewServer, transport.NewHandler)

var sessionSet = wire.NewSet(session.NewSessionManager, wire.Bind(
	new(transport.SessionManager),
	new(*session.SessionManager),
),
)

var handlerSet = wire.NewSet(handler.NewTransactionNotiHandler)
